/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yy_pillar_ffmpeg_FFmpegNative */

#ifndef _Included_com_yy_pillar_ffmpeg_FFmpegNative
#define _Included_com_yy_pillar_ffmpeg_FFmpegNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yy_pillar_ffmpeg_FFmpegNative
 * Method:    executeCmd
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yy_pillar_ffmpeg_FFmpegNative_executeCmd
  (JNIEnv *, jclass, jint, jobjectArray);

/*
 * Class:     com_yy_pillar_ffmpeg_FFmpegNative
 * Method:    avcodecinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yy_pillar_ffmpeg_FFmpegNative_avcodecinfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
